#-------------#
# Import Vars #
#-------------#
Import('*')

# Sources #
src = Split("""main.cpp
highscore.cpp
Libs/NFont.c
ReadKeyboard.cpp
joypad.cpp
listFiles.cpp
replay.cpp
stats.cc
common.cc
CppSdl/CppSdlImageHolder.cpp
CppSdl/CppSdlException.cpp""")

# Modify Build Environment #
env.ParseConfig('sdl-config --cflags --libs')
env.Append(CPPDEFINES = [('SHAREDIR', '\\"$sharedir\\"')])
env.Append(LIBS = ['SDL', 'enet','SDL_image','SDL_mixer','physfs'])
env.Append(LIBPATH = ['/usr/lib'])

# Compile Executable #
blockattack = env.Program('blockattack', src)
#Default(blockattack)

# Install blockattack itself
env.Install('$destdir/$bindir/', blockattack)
env.Alias('install', ['$destdir/$bindir/'])
