#-------------#
# Import Vars #
#-------------#
Import('*')

# Sources #
src = Split("""main.cpp
highscore.cpp
Libs/NFont.cpp
Libs/SDL_FontCache.cpp
sago/SagoDataHolder.cpp  
sago/SagoMisc.cpp  
sago/SagoSprite.cpp  
sago/SagoSpriteHolder.cpp
ReadKeyboard.cpp
joypad.cpp
listFiles.cpp
stats.cpp
common.cpp
MenuSystem.cpp
menudef.cpp
puzzlehandler.cpp""")

# Modify Build Environment #
env.ParseConfig('sdl2-config --cflags --libs')
env.Append(CPPDEFINES = [('SHAREDIR', '\\"$sharedir\\"')])
env.Append(LIBS = ['SDL2', 'enet','SDL2_image','SDL2_mixer','SDL2_ttf','physfs','jsoncpp'])
env.Append(LIBPATH = ['/usr/lib'])

# Compile Executable #
blockattack = env.Program('blockattack', src)
#Default(blockattack)

# Install blockattack itself
env.Install('$destdir/$bindir/', blockattack)
env.Alias('install', ['$destdir/$bindir/'])
