#-------------#
# Import Vars #
#-------------#
Import('*')

env.Install ('$destdir/$sharedir/',['blockattack.data'])
env.Alias('install',['$destdir/$sharedir'])

env.Install ('$destdir/$sharedir/res/',[
'puzzles/testPuzzles',
'puzzles/puzzle.levels'])
env.Alias('install', ['$destdir/$sharedir/res'])

