#-------------#
# Import Vars #
#-------------#
Import('*')

env.Install ('$destdir/$sharedir/gfx/smileys/',[
'blockattack.data'])
env.Alias('install',['$destdir/$sharedir'])

env.Install ('$destdir/$sharedir/res/',[
'res/testPuzzles',
'res/puzzle.levels'])
env.Alias('install', ['$destdir/$sharedir/res'])

