#!/bin/bash

# Move to script's directory
cd "`dirname "$0"`"

# Get the kernel/architecture information
ARCH=`uname -m`

# Set the libpath and pick the proper binary
if [ "$ARCH" == "x86_64" ]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./x86_64/
    ./x86_64/blockattack "$@"
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./x86/
    ./x86/blockattack "$@"
fi
