FROM ubuntu:20.04

# Set timezone to UTC. This prevents apt-get install SOME-PACKAGES from asking for timezone during setup
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


RUN apt-get update && apt-get install -yy build-essential libphysfs-dev libboost-dev libfmt-dev cmake libboost-program-options-dev libutfcpp-dev zip gettext libssl-dev
# SDL3 is not in Ubuntu 20.04 repos; CMake FetchContent will download and build SDL3 (BLOCKATTACK_DOWNLOAD_SDL3=ON by default)

RUN mkdir -p /staging/blockattack-game

COPY . /staging/blockattack-game

ENV BLOCKATTACK_VERSION 2.11.0-SNAPSHOT

RUN cd /staging/blockattack-game && \
./packdata.sh && \
cmake . && \
make
