FROM fedora:42

RUN dnf -y install cmake \
make \
gcc-c++ \
SDL2-devel \
boost-devel \
fmt-devel \
physfs-devel \
SDL2_image-devel SDL2_ttf-devel SDL2_mixer-devel \
findutils \
gettext \
zip \
&& dnf -y clean all

COPY . /staging/blockattack-game

ENV BLOCKATTACK_VERSION 2.10.0

RUN cd /staging/blockattack-game && \
./packdata.sh && \
cmake . && \
make
