FROM sago007/docker_blockattack

RUN mkdir -p /staging/blockattack-game

RUN mkdir -p /staging/package/

RUN mkdir -p /output

COPY . /staging/blockattack-game

ENV BLOCKATTACK_VERSION 2.7.0-SNAPSHOT

RUN cd /staging/blockattack-game && \
./packdata.sh && \
cp source/misc/travis_help/utf8_v2_3_4/source/utf8.h source/code/Libs/include/ && \
cp -r source/misc/travis_help/utf8_v2_3_4/source/utf8 source/code/Libs/include/ && \
i686-w64-mingw32.static-cmake . && \
make && \
cd windows\ installer/ && \
makensis install_script.nsi && \
mv Setup.exe /output/blockattack-installer-${BLOCKATTACK_VERSION}.exe && \
mkdir /staging/package/blockattack-${BLOCKATTACK_VERSION} && \
cd /staging/package/blockattack-${BLOCKATTACK_VERSION} && \
cp /staging/blockattack-game/Game/blockattack.data ./ && \
cp /staging/blockattack-game/Game/blockattack.exe ./ && \
cp /staging/blockattack-game/COPYING ./COPYING.txt && \
cp -r /staging/blockattack-game/source/misc/translation/locale ./ && \
echo "[InternetShortcut]" > "Block Attack - Rise Of the Blocks.url" && \
echo "URL=https://blockattack.net" >> "Block Attack - Rise Of the Blocks.url" && \
cd /staging/package/ && \
zip -r /output/blockattack-${BLOCKATTACK_VERSION}-windows-no-installer.zip "blockattack-${BLOCKATTACK_VERSION}" && \
cd /output && chown nobody * && chmod 666 * && ls -lh
