FROM ubuntu:18.04

RUN apt-get update && apt-get install -y software-properties-common

RUN add-apt-repository ppa:ubuntu-toolchain-r/test


RUN apt-get update && apt-get install -y build-essential cmake g++11 pkg-config libfreetype6-dev libvorbis-dev libgl1-mesa-dev libpulse-dev zip gettext


COPY source/misc/standalone/compile_requirements.sh /
RUN /compile_requirements.sh



COPY . /staging/blockattack-game

ENV BLOCKATTACK_VERSION 2.10.0-SNAPSHOT

RUN cd /staging/blockattack-game && \
./packdata.sh && \
cmake -D Boost_USE_STATIC_LIBS=ON -D INSTALL_DATA_DIR=. -D CMAKE_INSTALL_PREFIX=. -D STANDALONE=1 . && make
