FROM fedora:42

RUN dnf -y install cmake \
make \
gcc-c++ \
SDL3-devel \
boost-devel \
fmt-devel \
physfs-devel \
SDL3_image-devel SDL3_ttf-devel SDL3_mixer-devel \
findutils \
gettext \
zip \
&& dnf -y clean all

COPY . /staging/blockattack-game

ENV BLOCKATTACK_VERSION 2.11.0-SNAPSHOT

RUN cd /staging/blockattack-game && \
./packdata.sh && \
cmake . -DBLOCKATTACK_DOWNLOAD_SDL3=OFF && \
make
