FROM sago007/docker_blockattack

RUN apt-get update && apt-get install -y wixl wixl-data && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /staging/blockattack-game

RUN mkdir -p /staging/package/

RUN mkdir -p /staging/msi/

RUN mkdir -p /output

COPY . /staging/blockattack-game

ENV BLOCKATTACK_VERSION 2.11.0-SNAPSHOT

RUN cd /staging/blockattack-game && \
./packdata.sh && ls -lrt source/misc/embedded_libs/fmt-11.0.2 && \
i686-w64-mingw32.static-cmake . && \
make clean && make && \
cd windows\ installer/ && \
makensis install_script.nsi && \
mv Setup.exe /output/blockattack-installer-${BLOCKATTACK_VERSION}.exe && \
mkdir /staging/package/blockattack-${BLOCKATTACK_VERSION} && \
cd /staging/package/blockattack-${BLOCKATTACK_VERSION} && \
cp /staging/blockattack-game/Game/blockattack.data ./ && \
cp /staging/blockattack-game/Game/blockattack.exe ./ && \
cp /staging/blockattack-game/COPYING ./COPYING.txt && \
mkdir -p mods && cp /staging/blockattack-game/Game/mods/1.3.0.bricks.data ./mods/ && \
cp -r /staging/blockattack-game/source/misc/translation/locale ./ && \
echo "[InternetShortcut]" > "Block Attack - Rise Of the Blocks.url" && \
echo "URL=https://blockattack.net" >> "Block Attack - Rise Of the Blocks.url" && \
cd /staging/blockattack-game && \
find /staging/package/blockattack-${BLOCKATTACK_VERSION}/ -type f | \
wixl-heat -p /staging/package/blockattack-${BLOCKATTACK_VERSION}/ \
--component-group CG.blockattack --var var.SourceDir \
--directory-ref INSTALLDIR > /staging/msi/files.wxs && \
wixl -D SourceDir=/staging/package/blockattack-${BLOCKATTACK_VERSION} \
-D Version=${BLOCKATTACK_VERSION%%-*} \
"windows installer/msi/blockattack.wxs" /staging/msi/files.wxs \
-o /output/blockattack-${BLOCKATTACK_VERSION}.msi && \
cd /staging/package/ && \
zip -r /output/blockattack-${BLOCKATTACK_VERSION}-windows-no-installer.zip "blockattack-${BLOCKATTACK_VERSION}" && \
mv blockattack-${BLOCKATTACK_VERSION} blockattack-itch && \
zip -r /output/blockattack-itch-${BLOCKATTACK_VERSION}.zip "blockattack-itch" && \
cd /output && chown nobody * && chmod 666 * && ls -lh
